### ISSUE TITLE
Cannot read property 'queryid' of null

### ISSUE THREAD

**Issue by wyukawa** [tagomoris/shib#25]
The following error sometimes occurs.

shib log.
```
/.../shib/app.js:274
  q['queryid'] = query.queryid;
                      ^
TypeError: Cannot read property 'queryid' of null
    at pseudo_query_data (/.../shib/app.js:274:23)
    at null.<anonymous> (/.../shib/app.js:364:14)
    at /.../shib/lib/shib/client.js:193:14
    at Statement.<anonymous> (/.../shib/lib/shib/localdiskstore.js:153:17)
Mon Feb 23 2015 19:01:09 GMT+0900 (JST) [INFO] : Starting shib.
```

**Comment by tagomoris** [comment]
This issue seems to be fixed by #26.
Please reopen if not.
