### ISSUE TITLE
t_query.js/t_result.js test fails

### ISSUE THREAD

**Issue by achiku** [tagomoris/shib#29]
As I was preparing for the p-r (https://github.com/tagomoris/shib/issues/28), some tests failed, so this is roughly I checked. Any ideas?

### Summary

- ```shib/result.js``` 
    * This module dosen't exist in the repository, but tests still exist.
    * Maybe forgot to delete?
- ```instanciate``` 
    * Assertion errors, which seems like extected result is ```[]```, but ```Query.result``` is set to ```undefined``` if it's instanciated without arg.result.
    * https://github.com/tagomoris/shib/blob/master/lib/shib/query.js#L45-L48
    * https://github.com/tagomoris/shib/blob/master/lib/shib/query.js#L51-L78
- ```serialized```
    * queryid is different from expected value. I did't get into too deep to check this out.

```
$ node -v
v0.12.0
$ npm install
$ npm test
```

### stdout

```
> shib@1.0.0 test /Users/achiku/work/github/shib
> NODE_PATH=lib node_modules/nodeunit/bin/nodeunit test/*.js


t_access_control.js
✔ test1
✔ default_rule
✔ default_allowed
✔ default_denied

t_query.js
✔ test1
✔ removeNewLines
✔ removeNewLinesAndComments
✔ checkQueryString
✔ generateQueryId
✖ instanciate

AssertionError
    at Object.deepEqual (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.instanciate (/Users/achiku/work/github/shib/test/t_query.js:71:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

AssertionError
    at Object.deepEqual (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.instanciate (/Users/achiku/work/github/shib/test/t_query.js:76:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

AssertionError
    at Object.deepEqual (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.instanciate (/Users/achiku/work/github/shib/test/t_query.js:81:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

✖ serialized

AssertionError:
[ 'c148cdb90a70ef34dab88d8e1af967a6',
  '2015-03-07T08:45:27.252Z',
  null,
  undefined,
  undefined,
  'select f1,f2 from hoge_table',
  'running',
  '0996cea4fbff7e7caedab52e5f9d6e20',
  '{"error":"","lines":null,"bytes":null,"completed_at":null,"completed_msec":null,"schema":[]}' ]
deepEqual
'{"querystring":"select f1,f2 from hoge_table","results":[],"queryid":"c148cdb90a70ef34dab88d8e1af967a6"}'
    at Object.deepEqual (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.serialized (/Users/achiku/work/github/shib/test/t_query.js:87:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

AssertionError: '88db57a36ce1d24d1f5739a0c63f73dd' == 'c148cdb90a70ef34dab88d8e1af967a6'
    at Object.equals (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.serialized (/Users/achiku/work/github/shib/test/t_query.js:90:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

AssertionError
    at Object.equals (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.serialized (/Users/achiku/work/github/shib/test/t_query.js:91:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

AssertionError:
[ '2734efa50f0dff08129e3485b523f782',
  '2015-03-07T08:45:27.256Z',
  null,
  undefined,
  undefined,
  'select f1,f2 from hoge_table where service="news"',
  'running',
  '7decc7f94d9bdce8842211ad4c1ef7ca',
  '{"error":"","lines":null,"bytes":null,"completed_at":null,"completed_msec":null,"schema":[]}' ]
deepEqual
'{"querystring":"select f1,f2 from hoge_table where service=\\"news\\"","results":[],"queryid":"2734efa50f0dff08129e3485b523f782"}'
    at Object.deepEqual (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.serialized (/Users/achiku/work/github/shib/test/t_query.js:95:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

AssertionError: '88db57a36ce1d24d1f5739a0c63f73dd' == '2734efa50f0dff08129e3485b523f782'
    at Object.equals (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.serialized (/Users/achiku/work/github/shib/test/t_query.js:98:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

AssertionError
    at Object.equals (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testCase.serialized (/Users/achiku/work/github/shib/test/t_query.js:99:10)
    at Object.<anonymous> (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/lib/core.js:118:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:123:13)
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:134:25
    at /Users/achiku/work/github/shib/node_modules/nodeunit/deps/async.js:515:17

✔ composed
✔ parseTableNames
```

### stderr

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'shib/result'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/achiku/work/github/shib/test/t_result.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! Test failed.  See above for more details.
```

**Comment by tagomoris** [comment]
Several weeks ago, I skipped to fix tests on releasing shib v1. So failing tests is from my laziness.

* `shib/result` does NOT exist now. I forgot to delete its tests (and to add tests for shib/query).
* Now query has only a result, but related tests are not fixed yet.

There're many unfixed tests. I'll fix it ASAP, but not immediately (I don't have time to do it currently).

**Comment by achiku** [comment]
I understand what you mean, and yeah it's sometimes terribly painful to fix tests for already implemented functions. I can send quick p-r to fix tests, which may not to be fully adequate for whole functions. But I just want to have some tests to validate my p-r.

**Comment by achiku** [comment]
Spending some time digging into queryid generation and other features, it seems like resultset structure has been changed a lot. So I decided to wait till it's fixed in proper manner :)

In my another p-r, https://github.com/tagomoris/shib/pull/30, I just checked newly added tests pass and other tests, except being red due to releasing shib v1,  don't fail.

**Comment by tagomoris** [comment]
I fixed this issue and pushed it.
