### ISSUE TITLE
presto cancel error

### ISSUE THREAD

**Issue by wyukawa** [tagomoris/shib#61]
error log is the following. but I can't reproduce
```
Wed Jun 08 2016 18:39:08 GMT+0900 (JST) [WARN] : fetch error, { err: 
   { message: 'Query was canceled',
     errorCode: 3,
     errorName: 'USER_CANCELED',
     errorType: 'USER_ERROR',
     failureInfo: 
      { type: 'com.facebook.presto.spi.PrestoException',
        message: 'Query was canceled',
        suppressed: [],
        stack: [Object] } } }

/path/to/shib/lib/shib/engine.js:341
            if (rows === null || rows.length < 1 || (rows.length == 1 && rows[
                                     ^
TypeError: Cannot read property 'length' of undefined
    at /path/to/shib/lib/shib/engine.js:341:38
    at fill [as _onTimeout] (/path/to/shib/lib/shib/engines/presto/index.js:224:29)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by wyukawa** [comment]
maybe fixed in https://github.com/tagomoris/shib/pull/62
